Movie Recommnedation Based On Previously Watched + Similar Users watched

In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# sample vector similarity


v1 = [3.5, 2.5, 4]
v2 = [4, 5, 1]
v3 = [2, 1, 4]


X = [v1, v2, v3]

similarity = cosine_similarity(X)
similarity

array([[1.        , 0.80124558, 0.94737296],
       [0.80124558, 1.        , 0.57241978],
       [0.94737296, 0.57241978, 1.        ]])

In [3]:

movies = pd.read_csv("data/movies.csv")

movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
87580,292731,The Monroy Affaire (2022),Drama
87581,292737,Shelter in Solitude (2023),Comedy|Drama
87582,292753,Orca (2023),Drama
87583,292755,The Angry Breed (1968),Drama
87584,292757,Race to the Summit (2023),Action|Adventure|Documentary

In [4]:
ratings = pd.read_csv("data/ratings.csv")

ratings

          userId  movieId  rating   timestamp
0              1       17     4.0   944249077
1              1       25     1.0   944250228
2              1       29     2.0   943230976
3              1       30     5.0   944249077
4              1       32     5.0   943228858
...          ...      ...     ...         ...
32000199  200948    79702     4.5  1294412589
32000200  200948    79796     1.0  1287216292
32000201  200948    80350     0.5  1294412671
32000202  200948    80463     3.5  1350423800
32000203  200948    87304     4.5  1350423523

[32000204 rows x 4 columns]

In [5]:
movies = movies.head(1000)
ratings = ratings.head(100000)

In [6]:
ratings

       userId  movieId  rating   timestamp
0           1       17     4.0   944249077
1           1       25     1.0   944250228
2           1       29     2.0   943230976
3           1       30     5.0   944249077
4           1       32     5.0   943228858
...       ...      ...     ...         ...
99995     626      345     3.0  1111474319
99996     626      783     3.0  1111474327
99997     626     1285     2.5  1111474374
99998     626     1408     4.0  1111474255
99999     626     1674     2.5  1111474343

[100000 rows x 4 columns]

In [7]:
ratings["userId"].nunique()

626

In [8]:
user_data = ratings.pivot(index="userId", columns="movieId", values="rating").fillna(0)
user_data

movieId,1,2,3,4,5,6,7,8,9,10,...,287707,288265,288279,288513,288529,289317,289741,290263,290491,291485
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622,4.5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
623,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
624,0.0,0.0,0.0,0.0,4.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
user_similarity = cosine_similarity(user_data)
user_similarity

array([[1.        , 0.01375202, 0.10452492, ..., 0.04327624, 0.05232977,
        0.00830057],
       [0.01375202, 1.        , 0.2489614 , ..., 0.06585004, 0.06421778,
        0.07554806],
       [0.10452492, 0.2489614 , 1.        , ..., 0.14439323, 0.11625669,
        0.02938249],
       ...,
       [0.04327624, 0.06585004, 0.14439323, ..., 1.        , 0.38008611,
        0.00736044],
       [0.05232977, 0.06421778, 0.11625669, ..., 0.38008611, 1.        ,
        0.        ],
       [0.00830057, 0.07554806, 0.02938249, ..., 0.00736044, 0.        ,
        1.        ]], shape=(626, 626))

In [10]:
user_similarity.shape

(626, 626)

In [11]:
user_similarity_df = pd.DataFrame(user_similarity, index=user_data.index, columns=user_data.index)
user_similarity_df

userId,1,2,3,4,5,6,7,8,9,10,...,617,618,619,620,621,622,623,624,625,626
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.013752,0.104525,0.056688,0.037030,0.036693,0.037714,0.114014,0.106250,0.090086,...,0.029651,0.058180,0.092847,0.102437,0.047008,0.123706,0.134630,0.043276,0.052330,0.008301
2,0.013752,1.000000,0.248961,0.000000,0.351540,0.000000,0.371823,0.005829,0.019206,0.114095,...,0.479716,0.036671,0.096986,0.051115,0.312564,0.065511,0.102838,0.065850,0.064218,0.075548
3,0.104525,0.248961,1.000000,0.030175,0.358053,0.085106,0.231074,0.061530,0.054912,0.215408,...,0.205564,0.080521,0.094317,0.124287,0.268934,0.164809,0.174495,0.144393,0.116257,0.029382
4,0.056688,0.000000,0.030175,1.000000,0.000000,0.068642,0.000000,0.000000,0.037502,0.056632,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.051898,0.051051,0.000000,0.000000,0.000000
5,0.037030,0.351540,0.358053,0.000000,1.000000,0.027537,0.497770,0.072924,0.029776,0.168674,...,0.399280,0.114901,0.077698,0.207705,0.615385,0.093600,0.116623,0.054726,0.056536,0.051911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622,0.123706,0.065511,0.164809,0.051898,0.093600,0.045258,0.083562,0.215924,0.133540,0.376000,...,0.078650,0.226373,0.252733,0.284319,0.132303,1.000000,0.165663,0.286146,0.249877,0.000000
623,0.134630,0.102838,0.174495,0.051051,0.116623,0.038446,0.052247,0.085677,0.013551,0.161339,...,0.058190,0.058217,0.030068,0.134344,0.094261,0.165663,1.000000,0.043558,0.033536,0.042083
624,0.043276,0.065850,0.144393,0.000000,0.054726,0.045118,0.090994,0.145058,0.045034,0.238740,...,0.099233,0.084175,0.266217,0.212264,0.108875,0.286146,0.043558,1.000000,0.380086,0.007360
625,0.052330,0.064218,0.116257,0.000000,0.056536,0.032465,0.107780,0.208225,0.022993,0.191887,...,0.102259,0.159925,0.231210,0.282797,0.086218,0.249877,0.033536,0.380086,1.000000,0.000000
626,0.008301,0.075548,0.029382,0.000000,0.051911,0.000000,0.000000,0.000000,0.000000,0.023718,...,0.000000,0.000000,0.000000,0.000000,0.048686,0.000000,0.042083,0.007360,0.000000,1.000000

In [12]:
user_id = 49
user_vector = user_similarity_df[user_id]
user_vector

userId
1      0.046891
2      0.436029
3      0.329646
4      0.000000
5      0.756845
         ...
622    0.127581
623    0.142172
624    0.098651
625    0.105077
626    0.063802
Name: 49, Length: 626, dtype: float64

In [13]:
user_vector.sort_values(ascending=False)

userId
49     1.000000
5      0.756845
200    0.743607
607    0.694041
309    0.685584
         ...
257    0.000000
502    0.000000
501    0.000000
264    0.000000
314    0.000000
Name: 49, Length: 626, dtype: float64

In [14]:
user_ratings_row = user_data.loc[user_id]
user_ratings_row

movieId
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
         ...
289317    0.0
289741    0.0
290263    0.0
290491    0.0
291485    0.0
Name: 49, Length: 10225, dtype: float64

Show all movies this user watched and rated

In [15]:
for movie_id, rating in user_ratings_row.items():
    if rating > 0:
        print(f"User {user_id} rated movie {movie_id}", "Movie name:", movies[movies["movieId"] == movie_id]["title"].values[0], f"with a rating of {rating}")

User 49 rated movie 19 Movie name: Ace Ventura: When Nature Calls (1995) with a rating of 3.0
User 49 rated movie 21 Movie name: Get Shorty (1995) with a rating of 4.0
User 49 rated movie 34 Movie name: Babe (1995) with a rating of 4.0
User 49 rated movie 47 Movie name: Seven (a.k.a. Se7en) (1995) with a rating of 4.0
User 49 rated movie 110 Movie name: Braveheart (1995) with a rating of 5.0
User 49 rated movie 150 Movie name: Apollo 13 (1995) with a rating of 5.0
User 49 rated movie 153 Movie name: Batman Forever (1995) with a rating of 3.0
User 49 rated movie 161 Movie name: Crimson Tide (1995) with a rating of 3.0
User 49 rated movie 185 Movie name: Net, The (1995) with a rating of 4.0
User 49 rated movie 225 Movie name: Disclosure (1994) with a rating of 4.0
User 49 rated movie 231 Movie name: Dumb & Dumber (Dumb and Dumber) (1994) with a rating of 3.0
User 49 rated movie 253 Movie name: Interview with the Vampire: The Vampire Chronicles (1994) with a rating of 3.0
User 49 rated movie 288 Movie name: Natural Born Killers (1994) with a rating of 4.0
User 49 rated movie 292 Movie name: Outbreak (1995) with a rating of 4.0
User 49 rated movie 296 Movie name: Pulp Fiction (1994) with a rating of 5.0
User 49 rated movie 300 Movie name: Quiz Show (1994) with a rating of 3.0
User 49 rated movie 318 Movie name: Shawshank Redemption, The (1994) with a rating of 4.0
User 49 rated movie 339 Movie name: While You Were Sleeping (1995) with a rating of 4.0
User 49 rated movie 344 Movie name: Ace Ventura: Pet Detective (1994) with a rating of 3.0
User 49 rated movie 349 Movie name: Clear and Present Danger (1994) with a rating of 4.0
User 49 rated movie 356 Movie name: Forrest Gump (1994) with a rating of 5.0
User 49 rated movie 364 Movie name: Lion King, The (1994) with a rating of 5.0
User 49 rated movie 367 Movie name: Mask, The (1994) with a rating of 3.0
User 49 rated movie 377 Movie name: Speed (1994) with a rating of 4.0
User 49 rated movie 380 Movie name: True Lies (1994) with a rating of 3.0
User 49 rated movie 420 Movie name: Beverly Hills Cop III (1994) with a rating of 3.0
User 49 rated movie 434 Movie name: Cliffhanger (1993) with a rating of 3.0
User 49 rated movie 454 Movie name: Firm, The (1993) with a rating of 5.0
User 49 rated movie 457 Movie name: Fugitive, The (1993) with a rating of 4.0
User 49 rated movie 480 Movie name: Jurassic Park (1993) with a rating of 5.0
User 49 rated movie 500 Movie name: Mrs. Doubtfire (1993) with a rating of 4.0
User 49 rated movie 588 Movie name: Aladdin (1992) with a rating of 4.0
User 49 rated movie 589 Movie name: Terminator 2: Judgment Day (1991) with a rating of 3.0
User 49 rated movie 590 Movie name: Dances with Wolves (1990) with a rating of 3.0
User 49 rated movie 592 Movie name: Batman (1989) with a rating of 4.0
User 49 rated movie 593 Movie name: Silence of the Lambs, The (1991) with a rating of 5.0
User 49 rated movie 595 Movie name: Beauty and the Beast (1991) with a rating of 3.0

Illustration
each movie gets a score  based on similarity with the user and the rating the user has give

In [17]:
weighted_ratings = pd.Series(dtype=float)

count = 0
for sim_user, similarity_score in user_vector.items():
    count += 1
    # print(f"Sim user: {sim_user}, Similarity score: {similarity_score}")
    
    sim_user_ratings = user_data.loc[sim_user]
    weighted_ratings = weighted_ratings.add(sim_user_ratings * similarity_score, fill_value=0)
    print("count: ", count)

weighted_ratings

count:  1
count:  2
count:  3
count:  4
count:  5
count:  6
count:  7
count:  8
count:  9
count:  10
count:  11
count:  12
count:  13
count:  14
count:  15
count:  16
count:  17
count:  18
count:  19
count:  20
count:  21
count:  22
count:  23
count:  24
count:  25
count:  26
count:  27
count:  28
count:  29
count:  30
count:  31
count:  32
count:  33
count:  34
count:  35
count:  36
count:  37
count:  38
count:  39
count:  40
count:  41
count:  42
count:  43
count:  44
count:  45
count:  46
count:  47
count:  48
count:  49
count:  50
count:  51
count:  52
count:  53
count:  54
count:  55
count:  56
count:  57
count:  58
count:  59
count:  60
count:  61
count:  62
count:  63
count:  64
count:  65
count:  66
count:  67
count:  68
count:  69
count:  70
count:  71
count:  72
count:  73
count:  74
count:  75
count:  76
count:  77
count:  78
count:  79
count:  80
count:  81
count:  82
count:  83
count:  84
count:  85
count:  86
count:  87
count:  88
count:  89
count:  90
count:  91
count:  92
count:  93
count:  94
count:  95
count:  96
count:  97
count:  98
count:  99
count:  100
count:  101
count:  102
count:  103
count:  104
count:  105
count:  106
count:  107
count:  108
count:  109
count:  110
count:  111
count:  112
count:  113
count:  114
count:  115
count:  116
count:  117
count:  118
count:  119
count:  120
count:  121
count:  122
count:  123
count:  124
count:  125
count:  126
count:  127
count:  128
count:  129
count:  130
count:  131
count:  132
count:  133
count:  134
count:  135
count:  136
count:  137
count:  138
count:  139
count:  140
count:  141
count:  142
count:  143
count:  144
count:  145
count:  146
count:  147
count:  148
count:  149
count:  150
count:  151
count:  152
count:  153
count:  154
count:  155
count:  156
count:  157
count:  158
count:  159
count:  160
count:  161
count:  162
count:  163
count:  164
count:  165
count:  166
count:  167
count:  168
count:  169
count:  170
count:  171
count:  172
count:  173
count:  174
count:  175
count:  176
count:  177
count:  178
count:  179
count:  180
count:  181
count:  182
count:  183
count:  184
count:  185
count:  186
count:  187
count:  188
count:  189
count:  190
count:  191
count:  192
count:  193
count:  194
count:  195
count:  196
count:  197
count:  198
count:  199
count:  200
count:  201
count:  202
count:  203
count:  204
count:  205
count:  206
count:  207
count:  208
count:  209
count:  210
count:  211
count:  212
count:  213
count:  214
count:  215
count:  216
count:  217
count:  218
count:  219
count:  220
count:  221
count:  222
count:  223
count:  224
count:  225
count:  226
count:  227
count:  228
count:  229
count:  230
count:  231
count:  232
count:  233
count:  234
count:  235
count:  236
count:  237
count:  238
count:  239
count:  240
count:  241
count:  242
count:  243
count:  244
count:  245
count:  246
count:  247
count:  248
count:  249
count:  250
count:  251
count:  252
count:  253
count:  254
count:  255
count:  256
count:  257
count:  258
count:  259
count:  260
count:  261
count:  262
count:  263
count:  264
count:  265
count:  266
count:  267
count:  268
count:  269
count:  270
count:  271
count:  272
count:  273
count:  274
count:  275
count:  276
count:  277
count:  278
count:  279
count:  280
count:  281
count:  282
count:  283
count:  284
count:  285
count:  286
count:  287
count:  288
count:  289
count:  290
count:  291
count:  292
count:  293
count:  294
count:  295
count:  296
count:  297
count:  298
count:  299
count:  300
count:  301
count:  302
count:  303
count:  304
count:  305
count:  306
count:  307
count:  308
count:  309
count:  310
count:  311
count:  312
count:  313
count:  314
count:  315
count:  316
count:  317
count:  318
count:  319
count:  320
count:  321
count:  322
count:  323
count:  324
count:  325
count:  326
count:  327
count:  328
count:  329
count:  330
count:  331
count:  332
count:  333
count:  334
count:  335
count:  336
count:  337
count:  338
count:  339
count:  340
count:  341
count:  342
count:  343
count:  344
count:  345
count:  346
count:  347
count:  348
count:  349
count:  350
count:  351
count:  352
count:  353
count:  354
count:  355
count:  356
count:  357
count:  358
count:  359
count:  360
count:  361
count:  362
count:  363
count:  364
count:  365
count:  366
count:  367
count:  368
count:  369
count:  370
count:  371
count:  372
count:  373
count:  374
count:  375
count:  376
count:  377
count:  378
count:  379
count:  380
count:  381
count:  382
count:  383
count:  384
count:  385
count:  386
count:  387
count:  388
count:  389
count:  390
count:  391
count:  392
count:  393
count:  394
count:  395
count:  396
count:  397
count:  398
count:  399
count:  400
count:  401
count:  402
count:  403
count:  404
count:  405
count:  406
count:  407
count:  408
count:  409
count:  410
count:  411
count:  412
count:  413
count:  414
count:  415
count:  416
count:  417
count:  418
count:  419
count:  420
count:  421
count:  422
count:  423
count:  424
count:  425
count:  426
count:  427
count:  428
count:  429
count:  430
count:  431
count:  432
count:  433
count:  434
count:  435
count:  436
count:  437
count:  438
count:  439
count:  440
count:  441
count:  442
count:  443
count:  444
count:  445
count:  446
count:  447
count:  448
count:  449
count:  450
count:  451
count:  452
count:  453
count:  454
count:  455
count:  456
count:  457
count:  458
count:  459
count:  460
count:  461
count:  462
count:  463
count:  464
count:  465
count:  466
count:  467
count:  468
count:  469
count:  470
count:  471
count:  472
count:  473
count:  474
count:  475
count:  476
count:  477
count:  478
count:  479
count:  480
count:  481
count:  482
count:  483
count:  484
count:  485
count:  486
count:  487
count:  488
count:  489
count:  490
count:  491
count:  492
count:  493
count:  494
count:  495
count:  496
count:  497
count:  498
count:  499
count:  500
count:  501
count:  502
count:  503
count:  504
count:  505
count:  506
count:  507
count:  508
count:  509
count:  510
count:  511
count:  512
count:  513
count:  514
count:  515
count:  516
count:  517
count:  518
count:  519
count:  520
count:  521
count:  522
count:  523
count:  524
count:  525
count:  526
count:  527
count:  528
count:  529
count:  530
count:  531
count:  532
count:  533
count:  534
count:  535
count:  536
count:  537
count:  538
count:  539
count:  540
count:  541
count:  542
count:  543
count:  544
count:  545
count:  546
count:  547
count:  548
count:  549
count:  550
count:  551
count:  552
count:  553
count:  554
count:  555
count:  556
count:  557
count:  558
count:  559
count:  560
count:  561
count:  562
count:  563
count:  564
count:  565
count:  566
count:  567
count:  568
count:  569
count:  570
count:  571
count:  572
count:  573
count:  574
count:  575
count:  576
count:  577
count:  578
count:  579
count:  580
count:  581
count:  582
count:  583
count:  584
count:  585
count:  586
count:  587
count:  588
count:  589
count:  590
count:  591
count:  592
count:  593
count:  594
count:  595
count:  596
count:  597
count:  598
count:  599
count:  600
count:  601
count:  602
count:  603
count:  604
count:  605
count:  606
count:  607
count:  608
count:  609
count:  610
count:  611
count:  612
count:  613
count:  614
count:  615
count:  616
count:  617
count:  618
count:  619
count:  620
count:  621
count:  622
count:  623
count:  624
count:  625
count:  626

movieId
1         120.731695
2          66.657198
3          16.186031
4           4.868376
5          21.405957
             ...
289317      0.084293
289741      0.126440
290263      0.295026
290491      0.363895
291485      0.455304
Length: 10225, dtype: float64

In [20]:
weighted_ratings.sort_values(ascending=False)

movieId
356      245.719530
318      232.642928
296      228.435929
593      221.826981
480      194.086442
            ...
8754       0.000000
8757       0.000000
8782       0.000000
5279       0.000000
54185      0.000000
Length: 10225, dtype: float64

In [21]:
movvie_id =356
movie_name = movies[movies["movieId"] == movvie_id]["title"].values[0]
print(f"Movie ID: {movvie_id}, Movie name: {movie_name}")

Movie ID: 356, Movie name: Forrest Gump (1994)

In [22]:
user_rated = user_data.loc[user_id]
user_rated_movies = user_rated[user_rated > 0].index.tolist()
print("User rated movies:", user_rated_movies)

User rated movies: [19, 21, 34, 47, 110, 150, 153, 161, 185, 225, 231, 253, 288, 292, 296, 300, 318, 339, 344, 349, 356, 364, 367, 377, 380, 420, 434, 454, 457, 480, 500, 588, 589, 590, 592, 593, 595]

In [23]:
# Remove movies that the user has watched
weighted_ratings_after_removing_watched = weighted_ratings.drop(index=user_rated_movies, errors='ignore')

weighted_ratings_after_removing_watched

movieId
1         120.731695
2          66.657198
3          16.186031
4           4.868376
5          21.405957
             ...
289317      0.084293
289741      0.126440
290263      0.295026
290491      0.363895
291485      0.455304
Length: 10188, dtype: float64

In [25]:
weighted_ratings_after_removing_watched.sort_values(ascending=False)[:10]

movieId
527     161.755332
260     139.611475
50      136.936716
2571    133.976284
1       120.731695
1196    114.526668
165     113.094509
1210    108.421012
2959    108.111845
32      107.822163
dtype: float64